name: Scan Docker Repo
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
    
jobs:
  scan:
    name: List Recent Updates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Scan Docker Repository
        uses: dhet/scan-docker-tags-action@v1.0.1
        with:
          image: chetann/docker:v1
          max-age-minutes: 15
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        id: scan
      - name: Print
        run: "echo 'Recent updates: ${{ steps.scan.outputs.tags }}'"
